"""
Procedural PBR texturing for the wushi samurai (the source FBX ships without textures).

Every mesh already has a clean 0-1 UV atlas, so each texture is generated by rasterising the UV triangles and
evaluating a 3D-aware procedural material per pixel (object-space position, normal, curvature, bone-region).
Outputs per material: albedo (sRGB JPG), ORM (R=AO, G=roughness, B=metallic JPG) and a tangent-space normal map.

    import texturing; texturing.texture_scene(arm_obj, out_dir, quality)
"""
import bpy, os, math
import numpy as np
from mathutils import Vector

# --------------------------------------------------------------------------------------
# noise
# --------------------------------------------------------------------------------------
def _hash3(ix, iy, iz, seed=0):
    h = (ix.astype(np.int64) * 73856093) ^ (iy.astype(np.int64) * 19349663) ^ (iz.astype(np.int64) * 83492791) ^ (seed * 2654435761)
    h = (h ^ (h >> 13)) * 1274126177
    h = (h ^ (h >> 16)) & 0xFFFFFF
    return h.astype(np.float32) / float(0xFFFFFF)


def noise3(p, seed=0):
    ip = np.floor(p); f = (p - ip).astype(np.float32)
    f = f * f * (3 - 2 * f)
    ix, iy, iz = ip[..., 0], ip[..., 1], ip[..., 2]
    c = {}
    for dx in (0, 1):
        for dy in (0, 1):
            for dz in (0, 1):
                c[dx, dy, dz] = _hash3(ix + dx, iy + dy, iz + dz, seed)
    fx, fy, fz = f[..., 0], f[..., 1], f[..., 2]
    x00 = c[0, 0, 0] * (1 - fx) + c[1, 0, 0] * fx
    x10 = c[0, 1, 0] * (1 - fx) + c[1, 1, 0] * fx
    x01 = c[0, 0, 1] * (1 - fx) + c[1, 0, 1] * fx
    x11 = c[0, 1, 1] * (1 - fx) + c[1, 1, 1] * fx
    y0 = x00 * (1 - fy) + x10 * fy
    y1 = x01 * (1 - fy) + x11 * fy
    return y0 * (1 - fz) + y1 * fz


def fbm(p, oct=4, seed=0, lac=2.0, gain=0.5):
    a = 0.5; s = np.zeros(p.shape[:-1], np.float32); f = 1.0
    for o in range(oct):
        s += a * noise3(p * f, seed + o * 17); a *= gain; f *= lac
    return s


def smoothstep(a, b, x):
    t = np.clip((x - a) / (b - a + 1e-9), 0, 1)
    return t * t * (3 - 2 * t)


def mix(a, b, t):
    t = np.asarray(t, np.float32)
    ref = max(np.ndim(a), np.ndim(b))
    if t.ndim == ref - 1 or (ref == 1 and t.ndim >= 2): t = t[..., None]
    return a * (1 - t) + b * t


def col(r, g, b):
    return np.array([r, g, b], np.float32)


def srgb_to_lin(c): return np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)


# --------------------------------------------------------------------------------------
# UV rasteriser
# --------------------------------------------------------------------------------------
class Raster:
    pass


def rasterize(obj, arm, size, region_of_face):
    """returns Raster with pos(cm, armature space), nor, curv, reg, uv, mask arrays at size x size"""
    me = obj.data
    me.calc_loop_triangles()
    uvl = me.uv_layers.active.data
    mw = arm.matrix_world.inverted() @ obj.matrix_world
    nm = mw.to_3x3()
    verts = np.array([tuple(mw @ v.co) for v in me.vertices], np.float32)
    try:
        cn = np.array([tuple(c) for c in me.corner_normals.__iter__()], np.float32) if hasattr(me, 'corner_normals') else None
    except Exception:
        cn = None
    vn = np.array([tuple((nm @ v.normal).normalized()) for v in me.vertices], np.float32)
    H = W = size
    R = Raster()
    R.pos = np.zeros((H, W, 3), np.float32); R.nor = np.zeros((H, W, 3), np.float32) + np.array([0, 1, 0], np.float32)
    R.curv = np.zeros((H, W), np.float32); R.reg = np.zeros((H, W), np.int16)
    R.mask = np.zeros((H, W), bool); R.uv = np.zeros((H, W, 2), np.float32)
    # per vertex curvature: 1 - mean dot of normal with neighbour face normals
    fn = np.array([tuple(nm @ p.normal) for p in me.polygons], np.float32)
    acc = np.zeros(len(me.vertices), np.float32); cnt = np.zeros(len(me.vertices), np.float32)
    for p in me.polygons:
        for vi in p.vertices:
            acc[vi] += float(np.dot(fn[p.index], vn[vi])); cnt[vi] += 1
    vcurv = 1.0 - acc / np.maximum(cnt, 1)
    for t in me.loop_triangles:
        ls = t.loops; vs = t.vertices
        uv = np.array([(uvl[l].uv.x, uvl[l].uv.y) for l in ls], np.float32)
        px = uv[:, 0] * W - 0.5; py = (1 - uv[:, 1]) * H - 0.5
        x0, x1 = int(max(math.floor(px.min()) - 1, 0)), int(min(math.ceil(px.max()) + 1, W - 1))
        y0, y1 = int(max(math.floor(py.min()) - 1, 0)), int(min(math.ceil(py.max()) + 1, H - 1))
        if x1 < x0 or y1 < y0: continue
        gx, gy = np.meshgrid(np.arange(x0, x1 + 1), np.arange(y0, y1 + 1))
        d = (py[1] - py[2]) * (px[0] - px[2]) + (px[2] - px[1]) * (py[0] - py[2])
        if abs(d) < 1e-9: continue
        l0 = ((py[1] - py[2]) * (gx - px[2]) + (px[2] - px[1]) * (gy - py[2])) / d
        l1 = ((py[2] - py[0]) * (gx - px[2]) + (px[0] - px[2]) * (gy - py[2])) / d
        l2 = 1 - l0 - l1
        eps = -0.02
        m = (l0 >= eps) & (l1 >= eps) & (l2 >= eps)
        if not m.any(): continue
        yy, xx = gy[m], gx[m]
        b = np.stack([l0[m], l1[m], l2[m]], 1)[..., None]
        R.pos[yy, xx] = (b * verts[list(vs)][None]).sum(1)
        n = (b * vn[list(vs)][None]).sum(1); n /= np.maximum(np.linalg.norm(n, axis=1, keepdims=True), 1e-6)
        R.nor[yy, xx] = n
        R.curv[yy, xx] = (b[..., 0] * vcurv[list(vs)][None]).sum(1)
        R.reg[yy, xx] = region_of_face(t.polygon_index)
        R.mask[yy, xx] = True
        R.uv[yy, xx] = np.stack([(xx + 0.5) / W, 1 - (yy + 0.5) / H], 1)
    return R


def dilate(img, mask, iters=8):
    img = img.copy(); m = mask.copy()
    for _ in range(iters):
        grow = np.zeros_like(m)
        acc = np.zeros_like(img); cnt = np.zeros(m.shape, np.float32)
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1), (1, -1), (-1, 1)):
            sm = np.roll(m, (dy, dx), (0, 1)); si = np.roll(img, (dy, dx), (0, 1))
            use = sm & ~m
            acc[use] += si[use]; cnt[use] += 1
        fill = cnt > 0
        img[fill] = acc[fill] / cnt[fill][..., None] if img.ndim == 3 else acc[fill] / cnt[fill]
        m = m | fill
    return img


def height_to_normal(h, strength=2.0):
    gx = (np.roll(h, -1, 1) - np.roll(h, 1, 1)) * 0.5
    gy = (np.roll(h, -1, 0) - np.roll(h, 1, 0)) * 0.5
    n = np.stack([-gx * strength, gy * strength, np.ones_like(h)], -1)
    n /= np.linalg.norm(n, axis=-1, keepdims=True)
    return n * 0.5 + 0.5


# --------------------------------------------------------------------------------------
# material painters.  p = armature-space cm, region ids defined per mesh
# each returns dict(alb, rough, metal, height, ao)
# --------------------------------------------------------------------------------------
def _out(alb, rough, metal, height, ao=None):
    return dict(alb=np.clip(alb, 0, 1), rough=np.clip(rough, 0.04, 1), metal=np.clip(metal, 0, 1), height=height,
                ao=np.ones_like(rough) if ao is None else np.clip(ao, 0, 1))


def paint_armor(R, regs, plate_scale=3.4):
    """lacquered plates with crimson odoshi lacing; used for armo + Protective_L plates."""
    p = R.pos; u, v = R.uv[..., 0], R.uv[..., 1]
    big = fbm(p * 0.06, 4, 3); fine = fbm(p * 0.9, 3, 5); scr = np.abs(fbm(p * np.array([4.0, 0.4, 4.0], np.float32), 3, 9) - 0.5)
    lac = mix(col(0.035, 0.04, 0.075), col(0.075, 0.09, 0.15), big)           # indigo-black lacquer
    lac = lac * (0.88 + 0.24 * fine[..., None])
    # plate rows (horizontal gaps) and vertical lacing cords follow the UV grid of the atlas islands
    rowf = (v * 38.0) % 1.0
    groove = smoothstep(0.0, 0.06, rowf) * smoothstep(0.0, 0.06, 1 - rowf)
    cf = (u * (80.0 * plate_scale / 3.4)) % 1.0
    cord = smoothstep(0.26, 0.20, np.abs(cf - 0.5))
    braid = 0.5 + 0.5 * np.sin(v * 900.0 + np.sin(u * 40.0) * 2.0)
    crimson = mix(col(0.22, 0.012, 0.02), col(0.46, 0.05, 0.05), braid * 0.65 + 0.35 * fine)
    lace = cord * groove * (0.82 + 0.18 * fine)
    alb = mix(lac, crimson, lace * 0.92)
    rough = 0.30 + 0.22 * fine - 0.05 * big
    metal = np.full_like(rough, 0.18)
    height = groove * 0.5 + lace * 0.45 * (0.55 + 0.45 * braid)
    rough = np.where(lace > 0.5, 0.82, rough)
    metal = np.where(lace > 0.5, 0.0, metal)
    # worn edges -> gold/steel trim
    edge = smoothstep(0.10, 0.30, R.curv) * (0.5 + 0.5 * fbm(p * 1.8, 3, 11))
    gold = mix(col(0.62, 0.45, 0.16), col(0.38, 0.27, 0.09), fine)
    alb = mix(alb, gold, edge)
    rough = np.where(edge > 0.4, 0.28 + 0.25 * fine, rough)
    metal = np.where(edge > 0.4, 1.0, metal)
    height = height + edge * 0.35
    # scratches
    sc = smoothstep(0.012, 0.0, scr) * 0.25
    alb = alb * (1 + sc[..., None] * 0.9); rough = rough - sc * 0.1
    ao = 0.6 + 0.4 * groove
    return alb, rough, metal, height, ao


def paint_armo(R, rid):
    alb, rough, metal, height, ao = paint_armor(R, rid)
    p = R.pos
    # rope (tassels / belt cords) in cream
    rope = (R.reg == rid['rope'])
    cord = 0.5 + 0.5 * np.sin(p[..., 1] * 9 + p[..., 0] * 4 + p[..., 2] * 4)
    alb = np.where(rope[..., None], mix(col(0.78, 0.70, 0.52), col(0.55, 0.47, 0.32), cord), alb)
    rough = np.where(rope, 0.9, rough); metal = np.where(rope, 0.0, metal)
    height = np.where(rope, cord * 0.7, height)
    # chest/back: slightly warmer lacquer to read as the cuirass
    cu = (R.reg == rid['body'])
    alb = np.where(cu[..., None], alb * np.array([1.18, 1.0, 0.92], np.float32), alb)
    return _out(alb, rough, metal, height, ao)


def paint_neiyi(R, rid):
    p = R.pos
    fine = fbm(p * 0.7, 3, 21)
    big = fbm(p * 0.05, 3, 22)
    # twill weave from object-space coordinates (diagonal)
    u = (p[..., 0] + p[..., 2]) * 5.0; v = (p[..., 1] + (p[..., 0] - p[..., 2]) * 0.0) * 5.0
    weave = 0.5 + 0.25 * np.sin(u * 3.2) * np.sin(v * 3.2) + 0.25 * np.sin((u + v) * 1.6)
    base = mix(col(0.045, 0.06, 0.14), col(0.09, 0.11, 0.21), big)
    alb = base * (0.8 + 0.4 * weave[..., None]) * (0.9 + 0.2 * fine[..., None])
    # pale kasuri flecks
    fleck = smoothstep(0.78, 0.9, fbm(p * 2.4, 2, 23))
    alb = mix(alb, col(0.30, 0.34, 0.46), fleck * 0.35)
    rough = 0.88 - 0.1 * weave
    metal = np.zeros_like(rough)
    return _out(alb, rough, metal, weave * 0.8 + fine * 0.3, 0.8 + 0.2 * weave)


def paint_gloves(R, rid):
    p = R.pos; u, v = R.uv[..., 0], R.uv[..., 1]
    fine = fbm(p * 1.6, 3, 31); grain = fbm(p * 5.0, 2, 32); big = fbm(p * 0.1, 3, 33)
    leather = mix(col(0.17, 0.095, 0.05), col(0.28, 0.16, 0.08), big) * (0.85 + 0.3 * grain[..., None])
    rough = 0.55 + 0.25 * grain; metal = np.zeros_like(rough); height = grain * 0.5
    # stitching rows along island edges (high curvature)
    st = smoothstep(0.02, 0.08, R.curv)
    seam = (np.sin(p[..., 0] * 7 + p[..., 1] * 7 + p[..., 2] * 7) > 0.5) * st
    leather = mix(leather, col(0.55, 0.5, 0.4), seam * 0.6)
    # kote back-of-hand plate (UV top-left) and finger plates (UV top band)
    plate = (u < 0.40) & (v > 0.60)
    ring = (u > 0.42) & (v > 0.70)
    lac = mix(col(0.03, 0.035, 0.07), col(0.07, 0.08, 0.13), big)
    edge = smoothstep(0.03, 0.1, R.curv)
    plate_col = mix(lac, col(0.62, 0.45, 0.16), edge)
    steel = mix(col(0.22, 0.22, 0.24), col(0.4, 0.4, 0.42), fine)
    alb = np.where(plate[..., None], plate_col, np.where(ring[..., None], steel, leather))
    rough = np.where(plate | ring, 0.3 + 0.2 * fine, rough)
    metal = np.where(plate, 0.15 + 0.85 * edge, np.where(ring, 0.9, metal))
    return _out(alb, rough, metal, height + plate * edge * 0.5)


def paint_head(R, rid):
    p = R.pos; u, v = R.uv[..., 0], R.uv[..., 1]
    pores = fbm(p * 6.0, 2, 41); big = fbm(p * 0.18, 3, 42); veins = fbm(p * 1.2, 3, 43)
    skin = mix(col(0.52, 0.34, 0.25), col(0.64, 0.45, 0.34), big)
    skin = skin * (0.93 + 0.14 * pores[..., None])
    skin = mix(skin, col(0.62, 0.3, 0.26), smoothstep(0.62, 0.8, veins) * 0.25)
    rough = 0.52 + 0.18 * pores; metal = np.zeros_like(rough)
    alb = skin
    # facial features painted in UV space (eye / mouth loops of the atlas)
    def disc(cu, cv, r, soft=0.15):
        d = np.sqrt((u - cu) ** 2 + (v - cv) ** 2)
        return smoothstep(r, r * (1 - soft), d)
    for cu in (0.41, 0.535):
        sock = disc(cu, 0.688, 0.032, 0.6)
        alb = mix(alb, alb * 0.62, sock * 0.7)
        sclera = disc(cu, 0.688, 0.0185)
        alb = mix(alb, col(0.82, 0.8, 0.74), sclera)
        iris = disc(cu, 0.688, 0.0105)
        alb = mix(alb, col(0.10, 0.055, 0.035), iris)
        pupil = disc(cu, 0.688, 0.0048)
        alb = mix(alb, col(0.01, 0.01, 0.012), pupil)
        rough = np.where(sclera > 0.5, 0.15, rough)
        brow = disc(cu, 0.72, 0.03, 0.8) * (np.abs(v - 0.725) < 0.011)
        alb = mix(alb, col(0.03, 0.025, 0.02), brow * 0.9)
    lips = disc(0.4725, 0.578, 0.028, 0.5) * (np.abs(v - 0.578) < 0.012)
    alb = mix(alb, col(0.42, 0.18, 0.16), lips * 0.85)
    # stubble near jaw/mouth
    stub = smoothstep(0.55, 0.7, fbm(p * 8.0, 2, 44)) * smoothstep(0.62, 0.5, v) * 0.5
    alb = mix(alb, alb * 0.55, stub[..., None] if stub.ndim == 2 else stub)
    return _out(alb, rough, metal, pores * 0.6, 0.85 + 0.15 * pores)


def paint_helmet(R, rid):
    p = R.pos; y = p[..., 1]
    fine = fbm(p * 1.2, 3, 51); big = fbm(p * 0.07, 3, 52); scr = np.abs(fbm(p * np.array([5.0, 0.5, 5.0], np.float32), 3, 53) - 0.5)
    iron = mix(col(0.045, 0.047, 0.055), col(0.11, 0.115, 0.13), big) * (0.8 + 0.4 * fine[..., None])
    rough = 0.38 + 0.3 * fine; metal = np.full_like(rough, 0.85); height = fine * 0.3
    rivet = smoothstep(0.78, 0.9, noise3(p * 0.9, 55)) * smoothstep(0.03, 0.1, R.curv + 0.04)
    alb = mix(iron, col(0.3, 0.3, 0.32), rivet * 0.5)
    # crest (maedate): everything high above the skull in gold
    top = y > np.percentile(y[R.mask], 88) if R.mask.any() else y > 1e9
    gold = mix(col(0.78, 0.58, 0.18), col(0.45, 0.31, 0.08), fine)
    alb = np.where(top[..., None], gold, alb); metal = np.where(top, 1.0, metal); rough = np.where(top, 0.28, rough)
    # neck guard (low part): lacquered plates + crimson lacing
    low = y < np.percentile(y[R.mask], 28)
    a2, r2, m2, h2, ao2 = paint_armor(R, rid, 2.4)
    alb = np.where(low[..., None], a2, alb); rough = np.where(low, r2, rough); metal = np.where(low, m2, metal); height = np.where(low, h2, height)
    edge = smoothstep(0.04, 0.12, R.curv)
    alb = mix(alb, col(0.6, 0.45, 0.18), edge * (~top) * 0.7)
    sc = smoothstep(0.012, 0.0, scr) * 0.3
    alb = alb * (1 + sc[..., None]);
    return _out(alb, rough, metal, height)


def paint_mask(R, rid):
    p = R.pos; fine = fbm(p * 2.0, 3, 61); big = fbm(p * 0.2, 3, 62)
    red = mix(col(0.30, 0.025, 0.02), col(0.52, 0.06, 0.04), big) * (0.85 + 0.3 * fine[..., None])
    rough = 0.3 + 0.2 * fine; metal = np.full_like(rough, 0.1)
    # dark interior / nostril / moustache hints via vertical position
    edge = smoothstep(0.03, 0.1, R.curv)
    alb = mix(red, col(0.02, 0.015, 0.015), smoothstep(0.55, 0.8, fbm(p * 0.5, 3, 63)) * 0.55)
    alb = mix(alb, col(0.6, 0.45, 0.18), edge * 0.6)
    metal = np.where(edge > 0.4, 0.9, metal)
    return _out(alb, rough, metal, fine * 0.4)


def paint_prot(R, rid):
    alb, rough, metal, height, ao = paint_armor(R, rid, 2.8)
    p = R.pos
    shin = (R.reg == rid['leg'])
    fine = fbm(p * 1.4, 3, 71)
    iron = mix(col(0.07, 0.072, 0.082), col(0.2, 0.2, 0.22), fine)
    rv = smoothstep(0.8, 0.92, noise3(p * 0.8, 72))
    iron = mix(iron, col(0.45, 0.45, 0.47), rv * 0.6)
    keep = np.where(shin[..., None], mix(alb, iron, 0.55), alb)
    return _out(keep, np.where(shin, 0.38, rough), np.where(shin, 0.75, metal), height, ao)


def paint_sword(R, rid):
    """one atlas for the katana (blade/habaki/tsuba/tsuka/kashira)"""
    p = R.pos; reg = R.reg
    fine = fbm(p * 1.3, 3, 81); grain = fbm(p * np.array([0.8, 0.8, 8.0], np.float32), 3, 82)
    # sword-local: columns of position are armature-space of the *rest* mesh which was built in sword frame
    x, y, z = p[..., 0], p[..., 1], p[..., 2]
    steel = mix(col(0.62, 0.64, 0.68), col(0.82, 0.84, 0.88), fine) * (0.9 + 0.2 * grain[..., None])
    hamon = smoothstep(0.35, 0.8, x + 0.35 * np.sin(z * 0.5) * 0.9 + 0.3 * fbm(np.stack([z * 0.3, z * 0, z * 0], -1), 2, 83) * 2)
    steel = mix(steel * 0.85, steel * 1.1, hamon)
    alb = steel; rough = 0.2 + 0.2 * (1 - hamon) + 0.1 * fine; metal = np.ones_like(rough); height = grain * 0.1
    wrap = reg == rid['wrap']
    dia = (np.sin((z + y * 0.0) * 2.4) * np.sin(z * 2.4 + 1.6) > 0)
    ito = mix(col(0.04, 0.05, 0.10), col(0.10, 0.12, 0.22), dia.astype(np.float32))
    alb = np.where(wrap[..., None], ito * (0.9 + 0.2 * fine[..., None]), alb)
    rough = np.where(wrap, 0.75, rough); metal = np.where(wrap, 0.0, metal); height = np.where(wrap, dia.astype(np.float32) * 0.7, height)
    tsu = reg == rid['tsuba']
    alb = np.where(tsu[..., None], mix(col(0.03, 0.03, 0.03), col(0.18, 0.15, 0.1), fine)[..., :] if False else col(0.035, 0.032, 0.03) * (0.8 + 0.4 * fine[..., None]), alb)
    rough = np.where(tsu, 0.4, rough); metal = np.where(tsu, 0.9, metal)
    gold = reg == rid['gold']
    alb = np.where(gold[..., None], col(0.75, 0.55, 0.16), alb); rough = np.where(gold, 0.3, rough); metal = np.where(gold, 1.0, metal)
    lac = reg == rid['lacquer']
    sheen = mix(col(0.012, 0.011, 0.012), col(0.05, 0.04, 0.04), fine)
    alb = np.where(lac[..., None], sheen, alb); rough = np.where(lac, 0.16 + 0.06 * fine, rough); metal = np.where(lac, 0.05, metal)
    return _out(alb, rough, metal, height)


# --------------------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------------------
def _groups_for(obj):
    vg = {i: g.name for i, g in enumerate(obj.vertex_groups)}
    return vg


def _region_fn(obj, kind):
    me = obj.data; vg = _groups_for(obj)
    rid = {}
    out = np.zeros(len(me.polygons), np.int16)
    if kind in ('armo', 'prot', 'neiyi'):
        rid = {'body': 1, 'rope': 2, 'leg': 3, 'other': 0}
        for p in me.polygons:
            w = {}
            for vi in p.vertices:
                for g in me.vertices[vi].groups:
                    n = vg.get(g.group, '')
                    c = 'rope' if n.startswith('rope') else ('leg' if n.endswith(('leg', 'knee', 'ankle', 'foot', 'foottop')) else ('body' if n in ('HIP', 'spine', 'chest', 'neck') else 'other'))
                    w[c] = w.get(c, 0) + g.weight
            out[p.index] = rid[max(w, key=w.get)] if w else 0
    elif kind == 'sword':
        rid = {'steel': 0, 'tsuba': 1, 'gold': 2, 'wrap': 3, 'lacquer': 4}
        for p in me.polygons: out[p.index] = p.material_index
    else:
        rid = {}
    return rid, (lambda i: out[i])


PAINTERS = {
    'armo': ('armo', paint_armo, 2048), 'neiyi_': ('neiyi', paint_neiyi, 2048), 'glovesL': ('gloves', paint_gloves, 2048),
    'head_2': ('head', paint_head, 2048), 'helmet': ('helmet', paint_helmet, 2048), 'mask': ('mask', paint_mask, 1024),
    'Protective_L': ('prot', paint_prot, 2048), 'Katana': ('sword', paint_sword, 1024), 'Saya': ('sword', paint_sword, 1024),
}


def _save_img(name, arr, path, srgb, quality):
    h, w = arr.shape[:2]
    from PIL import Image
    im = Image.fromarray((np.clip(arr, 0, 1) * 255 + 0.5).astype(np.uint8))
    im.save(path, quality=quality, subsampling=0) if path.endswith('.jpg') else im.save(path, optimize=True)
    img = bpy.data.images.load(path, check_existing=False)
    img.name = name
    img.colorspace_settings.name = 'sRGB' if srgb else 'Non-Color'
    img.pack()
    return img


def make_material(name, alb_img, orm_img, nrm_img):
    m = bpy.data.materials.new(name); m.use_nodes = True
    nt = m.node_tree; nt.nodes.clear()
    out = nt.nodes.new('ShaderNodeOutputMaterial'); out.location = (800, 0)
    bsdf = nt.nodes.new('ShaderNodeBsdfPrincipled'); bsdf.location = (500, 0)
    nt.links.new(bsdf.outputs['BSDF'], out.inputs['Surface'])
    a = nt.nodes.new('ShaderNodeTexImage'); a.image = alb_img; a.location = (-400, 300); a.label = 'BaseColor'
    nt.links.new(a.outputs['Color'], bsdf.inputs['Base Color'])
    o = nt.nodes.new('ShaderNodeTexImage'); o.image = orm_img; o.location = (-700, 0); o.label = 'ORM'
    sep = nt.nodes.new('ShaderNodeSeparateColor'); sep.location = (-420, 0)
    nt.links.new(o.outputs['Color'], sep.inputs['Color'])
    nt.links.new(sep.outputs['Green'], bsdf.inputs['Roughness'])
    nt.links.new(sep.outputs['Blue'], bsdf.inputs['Metallic'])
    n = nt.nodes.new('ShaderNodeTexImage'); n.image = nrm_img; n.location = (-700, -300); n.label = 'Normal'
    nm = nt.nodes.new('ShaderNodeNormalMap'); nm.location = (-200, -300); nm.inputs['Strength'].default_value = 1.0
    nt.links.new(n.outputs['Color'], nm.inputs['Color'])
    nt.links.new(nm.outputs['Normal'], bsdf.inputs['Normal'])
    return m


def texture_scene(arm, out_dir, scale=1.0, quality=90, only=None):
    os.makedirs(out_dir, exist_ok=True)
    report = {}
    for on, (kind, fn, size) in PAINTERS.items():
        if only and on not in only: continue
        obj = bpy.data.objects.get(on)
        if obj is None or obj.type != 'MESH': continue
        if not obj.data.uv_layers:
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            bpy.ops.object.mode_set(mode='EDIT'); bpy.ops.mesh.select_all(action='SELECT')
            bpy.ops.uv.smart_project(angle_limit=math.radians(66), island_margin=0.01)
            bpy.ops.object.mode_set(mode='OBJECT')
        size = int(size * scale)
        rid, rf = _region_fn(obj, kind)
        R = rasterize(obj, arm, size, rf)
        m = fn(R, rid)
        alb = m['alb']; rough = m['rough']; metal = m['metal']; height = m['height']; ao = m['ao']
        orm = np.stack([ao, rough, metal], -1)
        nrm = height_to_normal(height.astype(np.float32), strength=float(max(1.0, size / 512.0)))
        alb = dilate(alb, R.mask); orm = dilate(orm, R.mask); nrm = dilate(nrm, R.mask)
        alb = np.where(R.mask[..., None], alb, np.array([0.1, 0.1, 0.1], np.float32))
        aimg = _save_img(f'{on}_albedo', alb, os.path.join(out_dir, f'{on}_albedo.jpg'), True, quality)
        oimg = _save_img(f'{on}_orm', orm, os.path.join(out_dir, f'{on}_orm.jpg'), False, quality)
        nimg = _save_img(f'{on}_normal', nrm, os.path.join(out_dir, f'{on}_normal.jpg'), False, 95)
        mat = make_material(f'tex_{on}', aimg, oimg, nimg)
        obj.data.materials.clear(); obj.data.materials.append(mat)
        for p in obj.data.polygons: p.material_index = 0
        report[on] = size
        print('textured', on, size, flush=True)
    return report
